from __future__ import annotations
import hashlib, json
from datetime import datetime, timezone
from typing import Any
from .version import APP_VERSION
VERSION=APP_VERSION
CONTRACT="lunar-planetary-intelligence"
def _now(): return datetime.now(timezone.utc).isoformat()
def _digest(v:Any)->str: return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
BODIES={
 "moon":{"title":"Moon","radius_km":1737.4,"trek_url":"https://trek.nasa.gov/moon/","api_url":"https://trek.nasa.gov/tiles/apidoc/trekAPI.html?body=moon","products":[
  {"id":"lro-wac-morphology","title":"LRO LROC WAC Global Morphology Mosaic","mission":"Lunar Reconnaissance Orbiter","instrument":"LROC Wide Angle Camera","product_type":"global image mosaic","resolution":"100 m/pixel product","coverage":"global morphology mosaic","source":"USGS Astrogeology Science Center","source_url":"https://astrogeology.usgs.gov/search/map/moon_lro_lroc_wac_global_morphology_mosaic_100m","quantitative_use":"visual/cartographic context; inspect source metadata before quantitative measurement"},
  {"id":"lro-wac-gld100","title":"LROC WAC GLD100 Color Shaded Relief","mission":"Lunar Reconnaissance Orbiter","instrument":"LROC WAC stereo / derived DTM","product_type":"color shaded topography","resolution":"118 m/pixel product","coverage":"79°S–79°N","source":"USGS Astrogeology Science Center","source_url":"https://astrogeology.usgs.gov/search/map/moon_lroc_wac_gld100_colorshade_79s79n_118m","quantitative_use":"derived topographic visualization; consult source DTM/metadata for measurement"},
  {"id":"kaguya-mi-reflectance","title":"SELENE/Kaguya MI Global Reflectance Mosaic","mission":"SELENE / Kaguya","instrument":"Multiband Imager","product_type":"reflectance mosaic","resolution":"237 m/pixel product","coverage":"global product","source":"USGS Astrogeology Science Center","source_url":"https://astrogeology.usgs.gov/search/map/moon_selene_kaguya_mi_global_reflectance_mosaic_237m","quantitative_use":"spectral/reflectance context; consult source processing metadata"}
 ]},
 "mars":{"title":"Mars","radius_km":3389.5,"trek_url":"https://trek.nasa.gov/mars/","api_url":"https://trek.nasa.gov/tiles/apidoc/trekAPI.html?body=mars","products":[
  {"id":"themis-controlled","title":"THEMIS Controlled Infrared Mosaics","mission":"2001 Mars Odyssey","instrument":"Thermal Emission Imaging System (THEMIS)","product_type":"controlled qualitative infrared mosaic","resolution":"100 m/pixel regional mosaics","coverage":"controlled mosaic system, principally ±65° latitude","source":"USGS Astrogeology Analysis Ready Data","source_url":"https://stac.astrogeology.usgs.gov/docs/data/mars/themis_controlled_mosaics/","quantitative_use":"8-bit controlled mosaics are qualitative; use individual science-ready images for quantitative analysis"},
  {"id":"mola-shaded-relief","title":"MGS MOLA Global Color Shaded Relief","mission":"Mars Global Surveyor","instrument":"Mars Orbiter Laser Altimeter (MOLA)","product_type":"derived global topographic relief","resolution":"463 m/pixel product","coverage":"global","source":"USGS Astrogeology Science Center","source_url":"https://astrogeology.usgs.gov/search/map/mars_mgs_mola_global_color_shaded_relief_463m","quantitative_use":"visualized topography; consult source elevation product for measurements"},
  {"id":"ctx-dtm","title":"MRO CTX Digital Terrain Models and Orthoimages","mission":"Mars Reconnaissance Orbiter","instrument":"Context Camera (CTX)","product_type":"local stereo DTM and orthoimage collection","resolution":"20 m DTM post spacing for listed products","coverage":"selected stereo-overlap regions, not global continuous coverage","source":"USGS Astrogeology STAC","source_url":"https://stac.astrogeology.usgs.gov/docs/data/mars/ctxdtms/","quantitative_use":"inspect QA metrics, MOLA alignment, gaps, jitter, and local artifacts before measurement"},
  {"id":"hirise-dtm","title":"MRO HiRISE DTMs and Orthoimages","mission":"Mars Reconnaissance Orbiter","instrument":"HiRISE","product_type":"high-resolution local DTM and orthoimage collection","resolution":"product dependent","coverage":"selected stereo observation footprints, not global","source":"USGS Astrogeology STAC","source_url":"https://stac.astrogeology.usgs.gov/docs/data/mars/hirise_dtms/","quantitative_use":"inspect QA and terrain-model artifacts before fine-scale measurement"}
 ]}
}
def overview():
 p={"ok":True,"version":VERSION,"contract":CONTRACT,"title":"Lunar & Planetary Intelligence","route":"earth","parent_contract":"orbital-earth-satellite-observation","destinations":["moon","mars"],"body_count":2,"summary":"Continue outward from Orbital Earth into source-aware lunar and Martian observation products without replacing mission imagery with decorative textures.","capabilities":["Moon and Mars destination state","mission/instrument/product provenance","official NASA Trek imagery handoff","USGS Astrogeology product evidence","body-specific coordinates","product coverage and resolution disclosure","planetary evidence manifest","surface/orbit/planetary continuity"],"truth_boundaries":["Site Intelligence does not label a decorative globe texture as mission imagery.","Official imagery is opened from registered NASA/USGS source services unless a verified raster service is connected.","Planetary coordinates are body-specific and are not Earth latitude/longitude observations.","Derived mosaics and terrain models may contain seams, gaps, interpolation, registration uncertainty, or processing artifacts.","A mission name does not imply that the displayed product is live or newly acquired."],"generated_at":_now()};p["contract_sha256"]=_digest(p);return p
def catalog():
 rows=[]
 for bid,b in BODIES.items():
  for pr in b["products"]: rows.append({"body_id":bid,"body_title":b["title"],**pr,"nasa_trek_url":b["trek_url"],"nasa_trek_api":b["api_url"],"live_claim":False})
 return {"ok":True,"version":VERSION,"contract":CONTRACT,"body_count":len(BODIES),"product_count":len(rows),"products":rows,"generated_at":_now()}
def body(body_id:str):
 bid=(body_id or "").lower();b=BODIES.get(bid)
 if not b:return {"ok":False,"version":VERSION,"contract":CONTRACT,"error":"unsupported planetary body","supported_bodies":list(BODIES)}
 p={"ok":True,"version":VERSION,"contract":CONTRACT,"body_id":bid,"body":b,"product_count":len(b["products"]),"generated_at":_now()};p["body_sha256"]=_digest(p);return p
def state(body_id="moon",product_id="",latitude=0.0,longitude=0.0,zoom=2.0):
 bid=body_id if body_id in BODIES else "moon";b=BODIES[bid];prod=next((x for x in b["products"] if x["id"]==product_id),b["products"][0]);lat=max(-90,min(90,float(latitude)));lon=((float(longitude)+180)%360)-180;z=max(1,min(12,float(zoom)))
 p={"ok":True,"version":VERSION,"contract":CONTRACT,"mode":"planetary","body_id":bid,"body_title":b["title"],"view":{"center":[lat,lon],"zoom":z,"coordinate_context":f"{b['title']} body-fixed cartographic coordinates","not_earth_coordinates":True},"observation":{**prod,"official_imagery_url":b["trek_url"],"official_trek_api":b["api_url"],"embedded_verified_raster":False,"presentation":"source-aware cartographic destination"},"truth":{"local_surface_texture_is_mission_imagery":False,"live_spacecraft_position_claimed":False,"real_time_acquisition_claimed":False,"official_source_handoff_available":True,"boundary":"The local planetary stage is navigation and evidence context. Use the registered NASA/USGS source link for mission imagery until a verified raster endpoint is connected."},"generated_at":_now()};p["state_sha256"]=_digest(p);return p
def export_manifest(body_id="moon",product_id="",latitude=0.0,longitude=0.0,zoom=2.0):
 s=state(body_id,product_id,latitude,longitude,zoom);return {"ok":True,"version":VERSION,"schema":"sc-site-intelligence-planetary-view/1.0","contract":CONTRACT,"planetary_state":s,"review":{"mission_imagery_fabricated":False,"official_source_link_preserved":True,"human_interpretation_required":True},"manifest_sha256":_digest(s),"generated_at":_now()}
def readiness():
 c={"moon_registered":"moon" in BODIES,"mars_registered":"mars" in BODIES,"nasa_trek_registered":all(v["trek_url"].startswith("https://trek.nasa.gov/") for v in BODIES.values()),"usgs_sources_registered":all(all("usgs.gov" in p["source_url"] for p in v["products"]) for v in BODIES.values()),"no_fake_imagery_claim":True,"no_live_telemetry_claim":True,"same_earth_route_preserved":True}
 p={"ok":all(c.values()),"version":VERSION,"contract":CONTRACT,"checks":c,"summary":{"route":"earth","bodies":len(BODIES),"products":sum(len(v["products"]) for v in BODIES.values())},"generated_at":_now()};p["readiness_sha256"]=_digest(p);return p
