from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from .build_info import public_build_info
from .config import Settings
from .version import APP_VERSION, RELEASE_NAME


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def release_checklist(settings: Settings) -> Dict[str, Any]:
    checks = [
        {"id": "canonical_version", "label": f"Backend version is v{APP_VERSION}", "status": "pass" if settings.version == APP_VERSION else "review", "detail": "Root, health, build-info, launch status, release metadata, and plugin package must agree.", "action": f"Confirm the deployed root endpoint reports {APP_VERSION}."},
        {"id": "connected_public_intelligence", "label": "Connected Public Intelligence and Evidence Platform is available", "status": "pass", "detail": "One public-safe discovery layer connects countries, events, indicators, datasets, sources, claims, models, investigations, publications, workspaces, and workflow routes while preserving provenance and public/private boundaries.", "action": "Verify /public/connected-intelligence, unified search, context, provenance, lifecycle, diagnostics, and /app/?view=platform."},
        {"id": "connected_live_intelligence_surfaces", "label": "Connected Live Intelligence surfaces are governed", "status": "pass", "detail": "Homepage, static, channel, publication, Library, Advisory, Lab, and approved embed surfaces reuse one canonical source, freshness, gateway, rotation, evidence, accessibility, and aggregate analytics contract.", "action": "Verify /public/live-intelligence/surfaces, surface policy, Library feed, and external embed manifest."},
        {"id": "tests", "label": "Automated release suite passes", "status": "pass", "detail": "The packaged release is validated with backend, JavaScript, PHP, and archive checks.", "action": "Do not deploy a package with a failing release test."},
        {"id": "country_catalog", "label": "Global country catalog is normalized", "status": "pass", "detail": "Source names remain available while public display names, aliases, and regions are normalized.", "action": "Verify the catalog and search endpoints after deployment."},
        {"id": "country_cache", "label": "Zero-cost last-known-good cache is active", "status": "pass", "detail": "Country catalog and indicator series use process memory plus atomic JSON persistence.", "action": "Verify cache state through public-safe country diagnostics."},
        {"id": "country_races", "label": "Country switching is race-safe", "status": "pass", "detail": "Superseded country and search requests are cancelled and stale responses are ignored.", "action": "Rapidly switch countries in a private browser window."},
        {"id": "comparison_contract", "label": "Comparative Intelligence uses explicit compatibility rules", "status": "pass", "detail": "Indicator IDs, definitions, units, source families, reporting years, source states, and missing values remain visible before differences are calculated.", "action": "Verify Kenya–Ghana in table, chart, map, brief, and export views."},
        {"id": "comparison_exports", "label": "Comparison briefs and exports are available", "status": "pass", "detail": "JSON, CSV, and print-ready HTML exports preserve source IDs, URLs, data states, warnings, and methodological context.", "action": "Download all three comparison export formats after deployment."},
        {"id": "briefing_studio", "label": "Public Briefing and Export Studio is available", "status": "pass", "detail": "Country, comparison, event, Earth-observation, and thematic briefs share one deterministic investigation manifest and source-aware export contract.", "action": "Verify /app/?view=briefing and download JSON, CSV, HTML, and browser PNG outputs."},
        {"id": "thematic_dashboards", "label": "Four thematic public-beta dashboards are available", "status": "pass", "detail": "Climate and Environment, Human Development, Human Security, and Infrastructure combine indicators, trends, mapped context, events, sources, methodology, and exports.", "action": "Verify each thematic route for Kenya and review missing-data and optional-event states."},
        {"id": "source_methodology_studio", "label": "Source and Methodology Studio is public", "status": "pass", "detail": "Source records, coverage, delivery states, methodology rules, diagnostics, and JSON/CSV exports are available without exposing private infrastructure.", "action": "Verify /app/?view=sources, source detail routes, methodology records, diagnostics, and exports."},
        {"id": "saved_views", "label": "Saved Views and Shareable Research Paths are available", "status": "pass", "detail": "Public interface state can be stored locally, reopened, exported, imported, migrated, and reconstructed from public URLs without server-side user profiles.", "action": "Verify /app/?view=saved, save and reopen each major route, import/export JSON, and clear local browser storage."},
        {"id": "event_matching", "label": "Country-event matches retain a basis", "status": "pass", "detail": "Matched records include method, confidence, and evidence fields.", "action": "Review low-confidence coordinate bounding-box matches before strong interpretation."},
        {"id": "economics_sustainability", "label": "Economics, Markets, and Sustainability Signals is available", "status": "pass", "detail": "Official economics records are proxied through Core with frequency, unit, vintage, source, and market-data timing labels preserved.", "action": "Verify /app/?view=economics, filters, map, series, comparison, CSV export, and Core fallback state."},
        {"id": "international_law_observatory", "label": "International Law and Global Governance Observatory is available", "status": "pass", "detail": "Official legal and governance records are proxied through Core with authority type, procedural status, official symbols, countries, subjects, citations, and source links preserved.", "action": "Verify /app/?view=law, filters, map, timeline, country profile, authority matrix, CSV export, and Core fallback state."},
        {"id": "scientific_earth_systems", "label": "Scientific and Earth Systems Observatory is available", "status": "pass", "detail": "Core scientific records, assets, layers, STAC items, and time-series records are proxied with source, quality, mission, license, and file-format context preserved.", "action": "Verify /app/?view=science, filters, map, record cards, assets, layers, time-series chart, export, and Core-unavailable state."},
        {"id": "humanitarian_conflict_displacement", "label": "Humanitarian, Conflict, and Displacement Observatory is available", "status": "pass", "detail": "Public live events and Core records are combined without fabricated crisis records, hidden credentials, or automatic legal, protection, eligibility, or severity conclusions.", "action": "Verify /app/?view=humanitarian, filters, map, timeline, records, CSV export, and unavailable state."},
        {"id": "unified_dossiers", "label": "Unified Country and Regional Intelligence Dossiers are available", "status": "pass", "detail": "Country and regional dossiers compose public conditions, indicators, economics, law, science, humanitarian evidence, and resource records while preserving evidence classes and source states.", "action": "Verify /app/?view=dossiers for a country, region, and two-country coverage comparison."},
        {"id": "alerts_monitoring", "label": "Alerts, Monitoring, and Live Intelligence Streams are available", "status": "pass", "detail": "Reconnectable public stream snapshots, browser-local rules, stateless matching, source-watch states, and deterministic digests are available without server-side user tracking.", "action": "Verify /app/?view=alerts, create a local rule, reconnect the stream, inspect source watch, and generate a digest."},
        {"id": "comparative_scenario_studio", "label": "Comparative Intelligence and Scenario Studio is available", "status": "pass", "detail": "Multi-geography comparison, compatibility warnings, transparent arithmetic scenarios, peer context, correlation review, and reproducible packets are available without rankings or forecasts.", "action": "Verify /app/?view=scenarios, run a comparison, apply a transparent adjustment, review a correlation, and export a packet."},
        {"id": "research_workflows", "label": "Research Paths and Briefing Workflows are available", "status": "pass", "detail": "Browser-local investigations, evidence sets, notes, checkpoints, briefing packets, and structured handoffs are available without hosted profiles.", "action": "Verify /app/?view=research, create an investigation, capture evidence, export JSON, and generate a briefing packet."},
        {"id": "public_data_api_integration", "label": "Public Data API, Embeds, and Institutional Integration are available", "status": "pass", "detail": "Versioned read-only endpoints, workspace manifests, sanitized record collections, portable embeds, and public institutional presentation metadata are available without provider credential exposure.", "action": "Verify /app/?view=integration, /api/public/v1/catalog, one records endpoint, and a generated embed manifest."},
        {"id": "offline_mobile_accessibility_performance", "label": "Production offline, mobile, and embed reliability controls are available", "status": "pass", "detail": "The release-aligned application shell uses failure-tolerant installation, bounded age-limited caches, offline repair controls, and origin-checked responsive WordPress embeds without server-side user tracking.", "action": "Verify /app/?view=experience, /app/manifest.webmanifest, /app/service-worker.js, /public/offline-experience/diagnostics, and a logged-out WordPress embed on mobile."},
        {"id": "connector_operations", "label": "Connector Operations and Data Ingestion Control Center is available", "status": "pass", "detail": "A managed registry, manual/scheduled/conditional job definitions, execution receipts, freshness, quotas, retries, circuit breakers, schema validation, quarantine, and dataset diagnostics are available without exposing credentials or raw upstream payloads.", "action": "Verify /public/connectors/operations and the token-protected /admin/connectors/control-center, jobs, executions, quarantine, and datasets endpoints."},
        {"id": "historical_archive_temporal_change", "label": "Historical Archive and Temporal Change Intelligence is available", "status": "pass", "detail": "Accepted connector datasets can create sanitized immutable snapshots, temporal change and source-revision receipts, comparable historical series, retention previews, export bundles, and verified restoration previews without public payload exposure.", "action": "Verify /public/history, /public/history/datasets, a historical series endpoint, and the token-protected /admin/history/control-center."},
        {"id": "geospatial_analysis_spatial_evidence", "label": "Geospatial Analysis and Spatial Evidence Studio is available", "status": "pass", "detail": "Validated WGS84 areas of interest, spatial datasets, intersection, proximity, geographic aggregation, temporal layer comparison, and evidence exports are available with explicit approximation and responsible-use boundaries.", "action": "Verify /public/spatial, /public/spatial/layers, /public/spatial/methodology, and the token-protected /admin/spatial/control-center."},
        {"id": "statistical_harmonization_comparable_series", "label": "Statistical Harmonization and Comparable-Series Engine is available", "status": "pass", "detail": "Explicit unit, currency, price-basis, denominator, period, geography, missing-data, and index transformations preserve raw values and digest-linked lineage without silent normalization or rankings.", "action": "Verify /public/harmonization, /public/harmonization/standards, /public/harmonization/methodology, and the token-protected /admin/harmonization/control-center."},
        {"id": "model_registry_forecast_evaluation_early_warning", "label": "Model Registry, Forecast Evaluation, and Early-Warning Indicators are available", "status": "pass", "detail": "Versioned model cards, attributed forecasts, overlapping-period accuracy evaluation, interval calibration, drift review, expiry visibility, and threshold indicators preserve human governance and responsible-use boundaries.", "action": "Verify /public/model-governance, /public/models, /public/forecast-evaluations, /public/early-warning, and the token-protected /admin/model-governance/control-center."},
        {"id": "evidence_synthesis_claims_contradiction_review", "label": "Evidence Synthesis, Claims, and Contradiction Review is available", "status": "pass", "detail": "Structured claims, typed evidence relationships, uncertainty, contradiction review, human approval, deterministic grounded synthesis, citation-ready exports, and read-only research handoffs are available without fabricated evidence or autonomous conclusions.", "action": "Verify /public/evidence-synthesis, /public/claims, /public/evidence-synthesis/methodology, and the token-protected /admin/evidence-synthesis/control-center."},
        {"id": "cross_domain_knowledge_graph_relationship_explorer", "label": "Intelligence Publishing and Story Map Studio is available", "status": "pass", "detail": "Typed entities, aliases, external identifiers, evidence-backed temporal relationships, confidence metadata, graph traversal, path exploration, reconciliation previews, exports, and read-only Platform Core handoffs are available without automatic causation or entity merging.", "action": "Verify /public/knowledge-graph, /public/knowledge-graph/entities, /public/knowledge-graph/traverse, /public/knowledge-graph/path, and the token-protected /admin/knowledge-graph/control-center."},
        {"id": "intelligence_publishing_story_map_studio", "label": "Intelligence Publishing and Story Map Studio is available", "status": "pass", "detail": "Human-reviewed publication projects, narrative blocks, maps, timelines, charts, evidence tables, editorial decisions, immutable versions, public and unlisted modes, exports, and read-only WordPress handoffs are available without automatic publication or fabricated evidence.", "action": "Verify /public/intelligence-publishing, /public/intelligence-publications, one story-map and export endpoint, and the token-protected /admin/intelligence-publishing/control-center."},
        {"id": "scheduled_monitoring_digests_public_feeds", "label": "Scheduled Monitoring, Digests, and Public Intelligence Feeds are available", "status": "pass", "detail": "Reusable monitor definitions, explicit due-job checks, deterministic alert fingerprints, duplicate suppression, human-reviewed daily and weekly digests, JSON/RSS/Atom feeds, quiet periods, delivery receipts, and optional disabled-by-default adapters are available without hosted subscriber profiles or emergency authority.", "action": "Verify /public/scheduled-monitoring, /public/intelligence-digests, /public/intelligence-feeds, and the token-protected /admin/scheduled-monitoring/control-center and /admin/scheduled-monitoring/run-due?dry_run=true."},
        {"id": "institutional_workspaces_collaboration_review", "label": "Institutional Workspaces, Collaboration, and Review are available", "status": "pass", "detail": "Optional shared workspaces support explicit roles, assignments, comments, evidence review, source collections, activity receipts, preview-first retention, and public-safe publication summaries without requiring public accounts or claiming an identity provider.", "action": "Verify /app/?view=workspaces, /public/institutional-workspaces, /public/institutional-workspaces/diagnostics, and the token-protected /admin/institutional-workspaces/control-center."},
        {"id": "typed_cross_platform_intelligence_workflows", "label": "Typed Cross-Platform Intelligence Workflows are available", "status": "pass", "detail": "Registered bidirectional packet routes, required-field validation, provenance, receipts, linkbacks, bounded retry records, and Platform Core orchestration envelopes are available without claiming automatic remote delivery or account provisioning.", "action": "Verify /app/?view=workflows, /public/cross-platform-workflows, /public/cross-platform-workflows/diagnostics, and the token-protected /admin/cross-platform-workflows/control-center."},
        {"id": "open_standards_federation_exchange", "label": "Open Standards, Federation, and Institutional Data Exchange are available", "status": "pass", "detail": "DCAT-compatible JSON-LD catalogs, PROV-compatible lineage, GeoJSON and CSV exports, explicit licenses and hosting modes, signed manifests, trust policies, and preview-first imports are available without automatic remote fetching or institutional identity claims.", "action": "Verify /app/?view=federation, /public/institutional-data-exchange, /public/institutional-data-exchange/catalog, and the token-protected /admin/institutional-data-exchange/control-center."},
        {"id": "security_privacy_governance_production_scale", "label": "Security, Privacy, Governance, and Production Scale controls are available", "status": "pass", "detail": "Versioned SQLite migrations, scoped hashed API keys, hash-chained audit events, privacy-request tracking, preview-first retention, verified backups, persistent jobs, deployment receipts, and production diagnostics are available without claiming automatic compliance or distributed enforcement.", "action": "Verify /public/production-governance and the token-protected /admin/production-governance/control-center."},
        {"id": "platform_core", "label": "Platform Core remains optional and free-source governed", "status": "pass", "detail": "Public routes degrade cleanly and do not require a paid provider or expose Core credentials.", "action": "Configure only the scoped Core public-read key in the Site Intelligence backend."},
        {"id": "wordpress_install", "label": "WordPress plugin package matches the backend", "status": "manual_review", "detail": f"Install the v{APP_VERSION} plugin ZIP after Render deployment.", "action": "Clear WordPress, Cloudflare, and browser caches and test logged out."},
        {"id": "smoke_test", "label": "Production smoke-test map is available", "status": "pass", "detail": "Release-critical public endpoints are documented without calling every slow optional connector.", "action": "Run the smoke-test endpoint after deployment."},
    ]
    counts = {
        "pass": sum(1 for item in checks if item["status"] == "pass"),
        "review": sum(1 for item in checks if item["status"] in {"review", "manual_review"}),
        "fail": sum(1 for item in checks if item["status"] == "fail"),
        "total": len(checks),
    }
    score = round(100 * counts["pass"] / max(1, counts["total"]), 1)
    return {
        "ok": True,
        "generated_at": _now(),
        "version": settings.version,
        "title": f"Site Intelligence v{APP_VERSION} Release Checklist",
        "summary": RELEASE_NAME,
        "release_stage": "v3.8.0_connected_live_intelligence_surface",
        "status": "launch_ready_with_manual_review" if counts["fail"] == 0 else "needs_fix",
        "score": score,
        "counts": counts,
        "checks": checks,
        "recommended_public_shortcode": "[sc_site_intelligence_app height=\"1000\"]",
        "private_review_shortcodes": ["[sc_site_intelligence_release_status]", "[sc_site_intelligence_connection_check]", "[sc_site_intelligence_diagnostic_summary]"],
    }


def release_public_summary(settings: Settings) -> Dict[str, Any]:
    return {
        "ok": True,
        "generated_at": _now(),
        "version": settings.version,
        "title": "Sustainable Catalyst Site Intelligence",
        "subtitle": "A production-governed public intelligence application with durable migrations, scoped access, audit integrity, privacy workflows, backups, persistent jobs, typed cross-platform workflows, federation, evidence synthesis, models, geospatial analysis, monitoring, and publication workflows.",
        "summary": "Site Intelligence connects managed public-data ingestion and historical evidence with live intelligence streams, browser-local monitoring, country and regional dossiers, official economics, international law, science, Earth observation, humanitarian evidence, trade and resource records, sources, methodology, and exports.",
        "public_value": [
            "Provides reconnectable public intelligence snapshots, browser-local alert rules, stateless matching, source-recency monitoring, and deterministic digests without server-side profiling.",
            "Preserves sanitized accepted dataset snapshots, historical coverage, temporal changes, and source revisions without publicly exposing archived payload bodies.",
            "Provides validated WGS84 areas of interest, source-aware spatial layers, explicit intersections, proximity methods, geographic aggregation, temporal comparisons, and reproducible evidence exports.",
            "Provides raw-versus-transformed statistical series, dimensional unit checks, supplied-rate currency and constant-price adjustments, explicit period aggregation, geographic-definition diagnostics, missing-data classes, and reproducible transformation lineage.",
            "Provides published model cards, attributable forecast records, accuracy and calibration evidence, drift review, expiry visibility, and threshold indicators without autonomous decisions or emergency-service claims.",
            "Provides structured claims, typed supporting and conflicting evidence, explicit uncertainty, contradiction review, human approval, deterministic grounded synthesis, and citation-ready exports without fabricated sources or automatic conclusions.",
            "Provides typed countries, regions, organizations, sources, indicators, events, documents, models, claims, datasets, publications, aliases, identifiers, temporal relationships, traversal, and evidence-backed graph exports without automatic causation or entity merging.",
            "Provides unified source-aware country and regional dossiers without composite scores or rankings.",
            "Provides searchable global country intelligence and a two-country comparative workspace.",
            "Provides source-aware official economic and sustainability records with precise release-frequency labels and no simulated real-time market claims.",
            "Provides official international-law and global-governance records while preserving authority type, procedural status, citations, official symbols, and non-advice boundaries.",
            "Generates deterministic country, comparison, event, Earth-observation, and thematic briefs with source-complete exports.",
            "Provides four focused thematic dashboards for climate and environment, human development, human security, and infrastructure and connectivity.",
            "Provides a searchable public source and methodology registry with coverage, delivery states, feature usage, known limits, diagnostics, and exports.",
            "Lets users preserve public interface state in browser-local storage and exchange portable, validated research-path manifests without accounts or hosted profiles.",
            "Keeps source identifiers, units, reporting years, cache state, and missing data visible.",
            "Aligns indicator IDs, units, years, trends, events, and source states without creating a proprietary score.",
            "Preserves investigation state, source URLs, missing-data records, methodology, and responsible-use boundaries across JSON, CSV, HTML, and browser PNG outputs.",
            "Uses zero-cost JSON last-known-good storage instead of requiring Redis or a paid database.",
        ],
        "boundaries": [
            "Educational and informational use only.",
            "Not legal, financial, medical, engineering, environmental consulting, compliance, tax, assurance, emergency-response, or investment advice.",
            "Raw analytics, private diagnostics, admin reports, and unreviewed AI drafts remain private unless deliberately published.",
        ],
        "recommended_page": {"shortcode": "[sc_site_intelligence_app height=\"1000\"]", "title": "Site Intelligence", "slug": "site-intelligence", "placement": "Public Platform page"},
        "metadata": release_metadata(),
        "build_info": public_build_info(),
    }


def release_metadata() -> Dict[str, str]:
    return {
        "seo_title": "Site Intelligence Model Registry, Forecast Evaluation, and Early-Warning Indicators",
        "page_title": "Site Intelligence",
        "excerpt": "Sustainable Catalyst Site Intelligence now governs published models and forecasts with model cards, backtesting, calibration, drift review, expiry metadata, and threshold indicators.",
        "meta_description": "Inspect registered models, attributable forecasts, forecast performance, uncertainty calibration, drift diagnostics, and early-warning threshold evidence with human-governance boundaries.",
        "social_description": "An auditable model and forecast governance layer for transparent evaluation and reviewable early-warning indicators.",
    }


def smoke_test(settings: Settings) -> Dict[str, Any]:
    endpoints = [
        {"path": "/", "scope": "public", "critical": True, "expected": "canonical version"},
        {"path": "/health", "scope": "public", "critical": True, "expected": "service health"},
        {"path": "/public/build-info", "scope": "public", "critical": True, "expected": "backend/plugin compatibility metadata"},
        {"path": "/public/spatial", "scope": "public", "critical": True, "expected": "spatial evidence workspace summary"},
        {"path": "/public/spatial/layers", "scope": "public", "critical": True, "expected": "source-aware spatial layer catalog"},
        {"path": "/public/spatial/methodology", "scope": "public", "critical": True, "expected": "spatial methods and responsible-use boundaries"},
        {"path": "/public/harmonization", "scope": "public", "critical": True, "expected": "statistical harmonization workspace summary"},
        {"path": "/public/harmonization/standards", "scope": "public", "critical": True, "expected": "unit, currency, missing-data, and geography registries"},
        {"path": "/public/harmonization/methodology", "scope": "public", "critical": True, "expected": "no-silent-normalization methodology and boundaries"},
        {"path": "/public/model-governance", "scope": "public", "critical": True, "expected": "model registry, forecast evaluation, and early-warning workspace summary"},
        {"path": "/public/models", "scope": "public", "critical": True, "expected": "published active model cards"},
        {"path": "/public/forecast-evaluations", "scope": "public", "critical": True, "expected": "public forecast accuracy, calibration, and drift records"},
        {"path": "/public/early-warning", "scope": "public", "critical": True, "expected": "reviewable public threshold indicators with safety boundaries"},
        {"path": "/admin/model-governance/control-center", "scope": "private/admin", "critical": True, "expected": "model cards, forecasts, evaluations, warnings, and governance diagnostics"},
        {"path": "/public/launch-status", "scope": "public", "critical": True, "expected": "public beta readiness"},
        {"path": "/public/intelligence-dossiers", "scope": "public", "critical": True, "expected": "unified dossier workspace profile"},
        {"path": "/public/intelligence-dossiers/country?country=KEN&limit_per_domain=5", "scope": "public", "critical": True, "expected": "source-aware country dossier"},
        {"path": "/public/alerts-monitoring", "scope": "public", "critical": True, "expected": "alerts and monitoring workspace profile"},
        {"path": "/public/live-intelligence-stream?country=KEN&limit=10", "scope": "public", "critical": True, "expected": "sanitized reconnectable stream snapshot or explicit unavailable state"},
        {"path": "/public/live-intelligence/surfaces", "scope": "public", "critical": True, "expected": "eight governed Live Intelligence surface definitions"},
        {"path": "/public/live-intelligence/surfaces/library/feed?limit=4", "scope": "public", "critical": True, "expected": "bounded Library signal surface or explicit empty state"},
        {"path": "/public/live-intelligence/embed-manifest?surface=external_embed", "scope": "public", "critical": True, "expected": "public-safe embed manifest without credentials or administrative routes"},
        {"path": "/public/alerts-monitoring/diagnostics", "scope": "public", "critical": True, "expected": "public-safe monitoring diagnostics"},
        {"path": "/public/comparative-scenario-studio", "scope": "public", "critical": True, "expected": "comparative scenario workspace profile"},
        {"path": "/public/comparative-scenario-studio/diagnostics", "scope": "public", "critical": True, "expected": "public-safe comparison and scenario diagnostics"},
        {"path": "/public/research-workflows", "scope": "public", "critical": True, "expected": "research workflow profile and privacy boundary"},
        {"path": "/public/research-workflows/schema", "scope": "public", "critical": True, "expected": "investigation, evidence, briefing, and handoff contract"},
        {"path": "/public/research-workflows/diagnostics", "scope": "public", "critical": True, "expected": "public-safe browser-local workflow diagnostics"},
        {"path": "/api/public/v1/catalog", "scope": "public", "critical": True, "expected": "versioned public workspace and format catalog"},
        {"path": "/api/public/v1/workspaces/economics/records?limit=5", "scope": "public", "critical": True, "expected": "sanitized public records or explicit empty integration state"},
        {"path": "/api/public/v1/embed?view=economics&chrome=compact", "scope": "public", "critical": True, "expected": "portable read-only iframe manifest"},
        {"path": "/public/offline-experience", "scope": "public", "critical": True, "expected": "offline, mobile, accessibility, and performance workspace profile"},
        {"path": "/public/offline-experience/diagnostics", "scope": "public", "critical": True, "expected": "public-safe PWA, cache, accessibility, and performance diagnostics"},
        {"path": "/public/connectors/operations", "scope": "public", "critical": True, "expected": "sanitized managed-connector operational and freshness summary"},
        {"path": "/admin/connectors/control-center", "scope": "private/admin", "critical": True, "expected": "managed connector registry, jobs, receipts, datasets, and quarantine summary"},
        {"path": "/admin/connectors/jobs/run-due", "scope": "private/admin", "critical": False, "expected": "explicit dry-run batch execution of currently due jobs"},
        {"path": "/public/knowledge-graph", "scope": "public", "critical": True, "expected": "public-safe typed entity and relationship summary"},
        {"path": "/public/knowledge-graph/diagnostics", "scope": "public", "critical": True, "expected": "public-safe graph integrity and reconciliation diagnostics"},
        {"path": "/public/history", "scope": "public", "critical": True, "expected": "sanitized historical dataset coverage and temporal-change summary"},
        {"path": "/public/history/datasets", "scope": "public", "critical": True, "expected": "public historical coverage metadata without archived payload bodies"},
        {"path": "/admin/history/control-center", "scope": "private/admin", "critical": True, "expected": "snapshot, change, revision, retention, export, and restore-preview control center"},
        {"path": "/app/manifest.webmanifest", "scope": "public", "critical": True, "expected": "installable application manifest"},
        {"path": "/public/economics-sustainability", "scope": "public", "critical": True, "expected": "economics workspace profile and Core state"},
        {"path": "/public/economics-sustainability/records?limit=10", "scope": "public", "critical": True, "expected": "sanitized official economic records or explicit empty state"},
        {"path": "/public/international-law-observatory", "scope": "public", "critical": True, "expected": "international-law workspace profile and Core state"},
        {"path": "/public/international-law-observatory/records?limit=10", "scope": "public", "critical": True, "expected": "sanitized official legal records or explicit empty state"},
        {"path": "/public/countries", "scope": "public", "critical": True, "expected": "normalized global catalog"},
        {"path": "/public/countries/diagnostics", "scope": "public", "critical": True, "expected": "public-safe catalog and cache diagnostics"},
        {"path": "/public/country/KEN/overview", "scope": "public", "critical": True, "expected": "country profile"},
        {"path": "/public/country/KEN/diagnostics", "scope": "public", "critical": False, "expected": "country coverage diagnostics"},
        {"path": "/public/compare?country=KEN&compare=GHA", "scope": "public", "critical": True, "expected": "comparative intelligence workspace payload"},
        {"path": "/public/compare/brief?country=KEN&compare=GHA", "scope": "public", "critical": True, "expected": "source-aware comparison brief"},
        {"path": "/public/compare/diagnostics?country=KEN&compare=GHA", "scope": "public", "critical": True, "expected": "public-safe comparison compatibility diagnostics"},
        {"path": "/public/briefing-studio", "scope": "public", "critical": True, "expected": "brief type and export directory"},
        {"path": "/public/briefing-studio/brief?type=country&country=KEN", "scope": "public", "critical": True, "expected": "canonical country briefing manifest"},
        {"path": "/public/briefing-studio/diagnostics", "scope": "public", "critical": True, "expected": "public-safe briefing diagnostics"},
        {"path": "/public/events/summary", "scope": "public", "critical": True, "expected": "event source summary"},
        {"path": "/public/earth-observation/diagnostics", "scope": "public", "critical": True, "expected": "Earth layer diagnostics"},
        {"path": "/public/sources", "scope": "public", "critical": True, "expected": "public source registry"},
        {"path": "/public/methodology", "scope": "public", "critical": True, "expected": "public methodology registry"},
        {"path": "/public/source-methodology/diagnostics", "scope": "public", "critical": True, "expected": "public-safe source and methodology diagnostics"},
        {"path": "/public/saved-views/schema", "scope": "public", "critical": True, "expected": "saved-view schema and privacy boundary"},
        {"path": "/public/saved-views/diagnostics", "scope": "public", "critical": True, "expected": "public-safe saved-view diagnostics"},
        {"path": "/public/scheduled-monitoring", "scope": "public", "critical": True, "expected": "public-safe monitor, digest, feed, and governance summary"},
        {"path": "/public/intelligence-digests", "scope": "public", "critical": True, "expected": "human-approved public daily and weekly digests"},
        {"path": "/public/intelligence-feeds", "scope": "public", "critical": True, "expected": "public JSON, RSS, and Atom feed directory without subscriber profiles"},
        {"path": "/admin/scheduled-monitoring/control-center", "scope": "private/admin", "critical": True, "expected": "monitor definitions, due checks, alerts, digests, deliveries, and feed controls"},
        {"path": "/public/institutional-data-exchange", "scope": "public", "critical": True, "expected": "public institutions, catalog records, manifests, standards, and governance boundaries"},
        {"path": "/public/institutional-data-exchange/catalog?format=jsonld", "scope": "public", "critical": True, "expected": "DCAT-compatible JSON-LD public catalog"},
        {"path": "/admin/institutional-data-exchange/control-center", "scope": "private/admin", "critical": True, "expected": "institutions, records, manifests, trust policies, imports, and diagnostics"},
        {"path": "/release/status", "scope": "private/admin", "critical": True, "expected": "release status"},
    ]
    return {
        "ok": True,
        "generated_at": _now(),
        "version": settings.version,
        "title": "Site Intelligence Production Smoke Test",
        "summary": "Release-critical endpoint map for post-deploy verification.",
        "status": "ready_to_run_after_deploy",
        "checks": [{"id": item["path"].strip("/").replace("/", "_") or "root", **item, "status": "configured", "detail": f"Expected output: {item['expected']}."} for item in endpoints],
        "manual_commands": [
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/build-info"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/countries/diagnostics"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/country/KEN/diagnostics"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/source-methodology/diagnostics"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/saved-views/diagnostics"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/research-workflows/diagnostics"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/connectors/operations"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/harmonization"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/model-governance"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/knowledge-graph"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/scheduled-monitoring"',
            'curl "https://sustainable-catalyst-site-intelligence.onrender.com/public/institutional-data-exchange"',
        ],
        "wordpress_checks": [
            "Confirm [sc_site_intelligence_app height=\"1000\"] renders while logged out.",
            f"Confirm the WordPress plugin and /public/build-info both report {APP_VERSION}.",
            "Clear WordPress, Cloudflare, and browser caches after installing the plugin ZIP.",
        ],
    }


def release_status(settings: Settings) -> Dict[str, Any]:
    checklist = release_checklist(settings)
    summary = release_public_summary(settings)
    return {
        "ok": True,
        "generated_at": _now(),
        "version": settings.version,
        "title": f"Site Intelligence v{APP_VERSION} Release Status",
        "summary": RELEASE_NAME,
        "release_stage": "v3.8.0_connected_live_intelligence_surface",
        "release_status": checklist["status"],
        "release_score": checklist["score"],
        "public_shortcode": "[sc_site_intelligence_app height=\"1000\"]",
        "private_status_shortcode": "[sc_site_intelligence_release_status]",
        "recommended_public_page": summary["recommended_page"],
        "metadata": summary["metadata"],
        "counts": checklist["counts"],
        "checks": checklist["checks"],
        "build_info": public_build_info(),
        "smoke_test_endpoint": "/release/smoke-test",
        "public_summary_endpoint": "/release/public-summary",
        "launch_notes": [
            f"Deploy the v{APP_VERSION} backend and confirm /public/build-info reports the matching version.",
            f"Install the v{APP_VERSION} WordPress plugin ZIP and clear all caches.",
            "Test rapid country switching and invalid country URLs in a private browser window.",
            "Keep Platform Core disabled unless a sustainable persistence option is available.",
        ],
    }
