#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VALIDATION_TMP="$(mktemp -d "${TMPDIR:-/tmp}/site-intelligence-v1201-validation.XXXXXX")"
trap 'rm -rf "$VALIDATION_TMP"' EXIT

# Keep all validation-generated bytecode, pytest state, country-cache files,
# and optional Platform Core queue data outside the release tree.
export PYTHONPYCACHEPREFIX="$VALIDATION_TMP/pycache"
export SC_SI_COUNTRY_CACHE_PATH="$VALIDATION_TMP/country_last_known_good.json"
export SC_SI_PLATFORM_CORE_QUEUE_PATH="$VALIDATION_TMP/platform_core_queue.jsonl"

say() { printf '\n==> %s\n' "$*"; }
fail() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

say "Validating required release files"
for path in \
  README.md \
  CHANGELOG.md \
  backend/app/version.py \
  backend/tests/test_backend_compatibility_cache_reliability_v1201.py \
  wordpress-plugin/sustainable-catalyst-site-intelligence/sustainable-catalyst-site-intelligence.php \
  docs/BACKEND_COMPATIBILITY_ADMIN_CACHE_RELIABILITY_V1201.md \
  docs/RELEASE_MANIFEST_V1201.json; do
  [[ -e "$ROOT_DIR/$path" ]] || fail "Missing required release path: $path"
done

say "Checking canonical release markers"
grep -q 'APP_VERSION = "1.20.1"' "$ROOT_DIR/backend/app/version.py" || fail "Backend version mismatch"
grep -q 'Version: 1.20.1' "$ROOT_DIR/wordpress-plugin/sustainable-catalyst-site-intelligence/sustainable-catalyst-site-intelligence.php" || fail "Plugin header mismatch"
grep -q "const VERSION = '1.20.1';" "$ROOT_DIR/wordpress-plugin/sustainable-catalyst-site-intelligence/sustainable-catalyst-site-intelligence.php" || fail "Plugin constant mismatch"
grep -q 'BUILD_INFO_MISMATCH_TTL = 45' "$ROOT_DIR/wordpress-plugin/sustainable-catalyst-site-intelligence/sustainable-catalyst-site-intelligence.php" || fail "Mismatch TTL missing"
grep -q 'scsi_refresh_backend_version' "$ROOT_DIR/wordpress-plugin/sustainable-catalyst-site-intelligence/sustainable-catalyst-site-intelligence.php" || fail "Refresh action missing"

say "Running Python tests"
(
  cd "$ROOT_DIR/backend"
  python -m pytest -q -p no:cacheprovider
)

say "Compiling Python"
python -m compileall -q "$ROOT_DIR/backend/app"

say "Checking standalone JavaScript"
if command -v node >/dev/null 2>&1; then
  node --check "$ROOT_DIR/backend/public_app/assets/app.js"
fi

say "Checking WordPress JavaScript"
if command -v node >/dev/null 2>&1; then
  node --check "$ROOT_DIR/wordpress-plugin/sustainable-catalyst-site-intelligence/assets/sc-site-intelligence.js"
fi

say "Checking WordPress PHP"
if command -v php >/dev/null 2>&1; then
  php -l "$ROOT_DIR/wordpress-plugin/sustainable-catalyst-site-intelligence/sustainable-catalyst-site-intelligence.php"
fi

say "Checking forbidden release artifacts"
FORBIDDEN_DIRS="$(
  find "$ROOT_DIR" \
    -path "$ROOT_DIR/.git" -prune -o \
    -type d \( \
      -name .git -o \
      -name node_modules -o \
      -name __pycache__ -o \
      -name .pytest_cache -o \
      -name .venv -o \
      -name venv \
    \) -print
)"
if [[ -n "$FORBIDDEN_DIRS" ]]; then
  printf '%s\n' "$FORBIDDEN_DIRS"
  fail "Forbidden generated directory found."
fi

if find "$ROOT_DIR" -type f \( \
  -name '.env' -o \
  -name '*.pem' -o \
  -name '*.key' -o \
  -name 'country_last_known_good.json' -o \
  -name 'country_last_known_good.json.tmp' -o \
  -name 'platform_core_queue.jsonl' \
\) -print -quit | grep -q .; then
  fail "Forbidden runtime or secret-bearing file found."
fi

say "Checking private-key markers"
if grep -RIl --exclude='*.zip' --exclude='*.pdf' -E 'BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY' "$ROOT_DIR" | grep -q .; then
  fail "Private-key material detected."
fi

say "Site Intelligence v1.20.1 validation passed"
