const VERSION="scsi-v2.12.0";
const SHELL=`${VERSION}-shell`;
const DATA=`${VERSION}-data`;
const OFFLINE="/app/offline.html";
const SHELL_URLS=["/app/","/app/offline.html","/app/manifest.webmanifest","/app/assets/alerts-v280.css","/app/assets/alerts-v280.js","/app/assets/app.css","/app/assets/app.js","/app/assets/dossiers-v270.css","/app/assets/dossiers-v270.js","/app/assets/economics-v220.css","/app/assets/economics-v220.js","/app/assets/experience-v2120.css","/app/assets/experience-v2120.js","/app/assets/global-conditions-v210.css","/app/assets/global-conditions-v210.js","/app/assets/humanitarian-v250.css","/app/assets/humanitarian-v250.js","/app/assets/icon-192.png","/app/assets/icon-512.png","/app/assets/integration-v2110.css","/app/assets/integration-v2110.js","/app/assets/law-v230.css","/app/assets/law-v230.js","/app/assets/research-v2100.css","/app/assets/research-v2100.js","/app/assets/resources-v260.css","/app/assets/resources-v260.js","/app/assets/scenarios-v290.css","/app/assets/scenarios-v290.js","/app/assets/science-v240.css","/app/assets/science-v240.js"];
self.addEventListener("install",event=>{event.waitUntil(caches.open(SHELL).then(cache=>cache.addAll(SHELL_URLS)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("scsi-")&&!key.startsWith(VERSION)).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function networkFirst(request){const cache=await caches.open(DATA);try{const response=await fetch(request);if(response.ok)cache.put(request,response.clone());return response}catch(error){const cached=await cache.match(request);if(cached)return cached;throw error}}
async function staleWhileRevalidate(request){const cache=await caches.open(SHELL);const cached=await cache.match(request);const network=fetch(request).then(response=>{if(response.ok)cache.put(request,response.clone());return response}).catch(()=>null);return cached||network||Response.error()}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method !== "GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==="navigate"){event.respondWith(networkFirst(request).catch(()=>caches.match(OFFLINE)));return}if(url.pathname.startsWith("/app/assets/")||url.pathname==="/app/manifest.webmanifest"){event.respondWith(staleWhileRevalidate(request));return}if(url.pathname.startsWith("/public/")||url.pathname.startsWith("/api/public/")){event.respondWith(networkFirst(request));}});
self.addEventListener("message",event=>{if(event.data?.type==="SC_SI_CLEAR_OFFLINE"){event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("scsi-")).map(key=>caches.delete(key)))))}if(event.data?.type==="SKIP_WAITING")self.skipWaiting()});
